### ISSUE TITLE
Add EBSCO adapter to reporting.wellcomecollection.org

### ISSUE THREAD

**Issue by jcateswellcome** [wellcomecollection/catalogue-pipeline#2575] opened 2024-03-08 11:31 UTC
When we have implemented the EBSCO adapter we will have established a new data source. Library staff should be able to report on this as they can for other sources via reporting.wellcomecollection.org

**Comment by kenoir** [comment] 2024-06-05 13:11
Duplicate of https://github.com/wellcomecollection/platform/issues/5746

**Closed by kenoir** 2024-06-05 13:11 UTC
